cookiecutter-flask/cookiecutter-flask

{{cookiecutter.app_name}}/README.rst

Re: getting started for new users
Fixed a gotcha regards white space in an export and separated out the need to have a database installed before you can see the Welcome page working on localhost:5000.

Debugging get started guide

---

{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/public/views.py
{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/user/views.py

See mitsuhiko/flask#1135
Looks like flask.ext.* was missed to be updated on 2 files.

Update extension imports to flask_*

---

{{cookiecutter.app_name}}/tests/conftest.py

http://stackoverflow.com/questions/26350911/what-to-do-when-a-py-test-hangs-silently

fix db fixture for model tests

---

{{cookiecutter.app_name}}/README.rst

Fixes https://github.com/sloria/cookiecutter-flask/issues/62

Update README.rst to include bower install step

---

{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/app.py
{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/extensions.py
{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/templates/nav.html

- CSRF is enabled by default for login form
- This commit resolves issue #34

Enable CSRF protection

---

{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/templates/public/home.html
{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/templates/users/members.html

Refs Issue #119 replace session with current_user, remove unnecessary href

---

{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/extensions.py

FlaskWTFDeprecationWarning: "flask_wtf.CsrfProtect" has been renamed to "CSRFProtect" and will be removed in 1.0.
http://flask-wtf.readthedocs.io/en/stable/csrf.html

update CSRFProtect in extensions

---

{{cookiecutter.app_name}}/tests/conftest.py

https://docs.pytest.org/en/latest/yieldfixture.html

Deprecate pytest yield fixtures.

---

{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/public/forms.py
{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/user/forms.py

https://flask-wtf.readthedocs.io/en/latest/api.html#flask_wtf.Form
#nuisanceprs

Use `FlaskForm` instead of deprecated `Form`.

---

cookiecutter.json
tasks.py
{{cookiecutter.app_name}}/.env.example
{{cookiecutter.app_name}}/.travis.yml
{{cookiecutter.app_name}}/Dockerfile
{{cookiecutter.app_name}}/Pipfile
{{cookiecutter.app_name}}/README.rst
{{cookiecutter.app_name}}/docker-compose.yml
{{cookiecutter.app_name}}/package.json
{{cookiecutter.app_name}}/requirements/dev.txt
{{cookiecutter.app_name}}/requirements/prod.txt
{{cookiecutter.app_name}}/shell_scripts/auto_pipenv.sh
{{cookiecutter.app_name}}/shell_scripts/supervisord_entrypoint.sh
{{cookiecutter.app_name}}/supervisord.conf
{{cookiecutter.app_name}}/supervisord_programs/gunicorn.conf
{{cookiecutter.app_name}}/webpack.config.js

Submitting this PR in response to issue https://github.com/sloria/cookiecutter-flask/issues/65, as it doesn't seem like PR #272 has activity in > 1 year.
* Support for running the cookiecutter app in Docker
* User specifies desired Python and Node version during cookiecutter setup
* Separate production and development docker-compose services
* Production service leverages gunicorn and supervisord 
* Misc. Fixes & additions
*  `app_name` from the `cookiecutter.json` must be a valid Python module name, but there is no validation. The default is now the Python-friendly version of the `project_name` to reduce possibility for user error.
* PDB++ debugger

Implement docker environment

---

{{cookiecutter.app_name}}/Pipfile

Merge conflict wasn't fully resolved. Doh!

Bugfix pipfile

---

tasks.py
{{cookiecutter.app_name}}/docker-compose.yml
{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/app.py
{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/public/views.py

Fix logging issue

---

{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/database.py

Support passing custom sets of kwargs when creating a reference column

---

.gitignore
{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/app.py
{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/commands.py

* We're py3-only, so py[co] files won't get created
* Flask now has a built-in `flask routes` command

Remove unnecessary `clean` and `urls` commands

---

{{cookiecutter.app_name}}/webpack.config.js

Fixes #509 courtesy of lamphej and brightgems.

Images missing in webpack 4

---

{{cookiecutter.app_name}}/requirements/dev.txt
{{cookiecutter.app_name}}/requirements/prod.txt

I've updated text files with requirements since **dependabot** updates only the **Pipfile**.

Update txt requirements

---

Dockerfile
{{cookiecutter.app_name}}/Dockerfile

Run docker container as non-root user

---

README.rst

There is occasionally confusion about where to find usage instructions (often it is assumed that they should live in the main project's README). This clarifies that usage instructions can be found in the README of the generated project.

Provide clarification on where to find usage instructions

---

README.rst

A bit more about the fact that you must do more bootstrapping, and where to find the instructions.

Tweaks to the post-generation README text

---

cookiecutter.json
hooks/post_gen_project.py
{{cookiecutter.app_name}}/.travis.yml
{{cookiecutter.app_name}}/Pipfile
{{cookiecutter.app_name}}/Procfile
{{cookiecutter.app_name}}/README.rst
{{cookiecutter.app_name}}/app.json
{{cookiecutter.app_name}}/package.json
{{cookiecutter.app_name}}/requirements/prod.txt

Enhanced support for Heroku deployment. Added description how to deploy by CLI or by clicking "Deploy to Heroku" button (from repository README file on github).
Reference to mentioned button:
https://devcenter.heroku.com/articles/heroku-button
Closes #207

Add Heroku deployment support

---

{{cookiecutter.app_name}}/Dockerfile

I think these need to match the structure on line 29. This seemed to fix the build issues I was having with the manage image

Add /home to pipenv manage folder structure

---

README.md

Hello! I am a university student taking a technical writing course. For one project we need to make suggested edits to repos on github. 
Please use the following suggestions at your discretion :)
- removed a few empty words
- reduced instances of contractions and pronouns (to increase clarity)

university student project edits

---

{{cookiecutter.app_name}}/webpack.config.js

Closes https://github.com/cookiecutter-flask/cookiecutter-flask/issues/654

Fix issue 654

---

{{cookiecutter.app_name}}/package.json

Upgrade babel-preset-env to @babel/preset-env

---

.github/workflows/autogen.yaml
README.md

Generate an actual version of the project for every PR that's merged to make it easier to browse the code & to catch issues with the generated project's CI pipeline that may not be caught by the unit tests of this repo.

Autobuild example project

---

{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/templates/nav.html

Fixes #923
Sorry I thought I opened that PR!

Route login POST request to public.home

---

{{cookiecutter.app_name}}/webpack.config.js

Fix issue where two config options were inadvertently combined into one

Fix file loader config

---

Dockerfile

Closes https://github.com/cookiecutter-flask/cookiecutter-flask/issues/993

Reset user in project generation image

---

.github/workflows/autogen.yaml
.github/workflows/lint.yaml
.github/workflows/scan.yaml
Dockerfile
cookiecutter.json
cookiecutter_spec.py
hooks/post_gen_project.py
requirements.txt
tasks.py
{{cookiecutter.app_name}}/.github/workflows/lint.yaml
{{cookiecutter.app_name}}/Dockerfile
{{cookiecutter.app_name}}/README.md
{{cookiecutter.app_name}}/package.json
{{cookiecutter.app_name}}/shell_scripts/supervisord_entrypoint.sh

Start using `columbo` to manage the question/answer portion of the cookiecutter generation, as it allows for more customizable prompts & a better UX.

Improve UX of cookiecutter question flow

---

{{cookiecutter.app_name}}/.eslintrc.js
{{cookiecutter.app_name}}/assets/js/main.js
{{cookiecutter.app_name}}/package.json
{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/templates/nav.html

Closes #1011
Closes #1120
Closes #1122

Update js deps

---

{{cookiecutter.app_name}}/tests/test_database.py
{{cookiecutter.app_name}}/tests/test_models.py
{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/database.py

Bring database.py and models.py test line coverage to 100% in generated project.
Provide 100% line coverage testing of database.py.
Refactor conditional statements to allow conditions to be seen explicitly during line coverage review.
Add tests for Role and User repr methods.

Additional tests

---

{{cookiecutter.app_name}}/README.md
{{cookiecutter.app_name}}/docker-compose.yml

MacOS is now reserving the use of port 5000

Change default port

---

{{cookiecutter.app_name}}/webpack.config.js

Fix webpack mode

---

{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/database.py

Adds a Type Var ["with generic self"](https://mypy.readthedocs.io/en/latest/generics.html#generic-methods-and-generic-self) for `PkModel.get_by_id `.
Closes #1235.

Adding Type Var for PkModel.get_by_id, closes #1235

---

{{cookiecutter.app_name}}/Pipfile
{{cookiecutter.app_name}}/requirements/dev.txt
{{cookiecutter.app_name}}/requirements/prod.txt

Closes https://github.com/cookiecutter-flask/cookiecutter-flask/pull/1352
Closes https://github.com/cookiecutter-flask/cookiecutter-flask/pull/1351
Closes https://github.com/cookiecutter-flask/cookiecutter-flask/pull/1350
Closes https://github.com/cookiecutter-flask/cookiecutter-flask/pull/1349
Closes https://github.com/cookiecutter-flask/cookiecutter-flask/pull/1346
Closes https://github.com/cookiecutter-flask/cookiecutter-flask/pull/1345
Closes https://github.com/cookiecutter-flask/cookiecutter-flask/pull/1343
Closes https://github.com/cookiecutter-flask/cookiecutter-flask/pull/1342

Update dependency versions

---

{{cookiecutter.app_name}}/Pipfile
{{cookiecutter.app_name}}/requirements/dev.txt
{{cookiecutter.app_name}}/requirements/prod.txt

Closes https://github.com/cookiecutter-flask/cookiecutter-flask/issues/1422

Sync dependencies between .txt files and Pipfile

---

{{cookiecutter.app_name}}/Pipfile
{{cookiecutter.app_name}}/requirements/dev.txt

Remove pdbpp

---

{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/templates/layout.html

The attribute is `data-bs-dismiss` in the Bootstrap 5 (see https://getbootstrap.com/docs/5.0/components/modal/)

Update dismiss attribute for Bootstrap 5
