cookiecutter-flask/cookiecutter-flask

{{cookiecutter.app_name}}/requirements/prod.txt

Flask-Migrate was recently patched to version 1.3.1 because [alembic versions can now include parts that are not integers](https://github.com/miguelgrinberg/Flask-Migrate/pull/51).
Requiring Flask-Migrate 1.3.0 installs a version of alembic that results in the following error message on startup:
`ValueError: invalid literal for int() with base 10: 'post2'`
Changing the requirements to install Flask-Migrate 1.3.1 fixes this problem.

Fix breaking change from Flask-Migrate

---

{{cookiecutter.app_name}}/tests/conftest.py

If you cookiecut a new project right now, `python manage.py test` will have a few failed tests. This fixes them so that everything passes from the start.
The `testapp` fixture depends on the `app` fixture, but the `app` fixture's
scope was redefined as 'function' in commit 35c32eccc10795d273634125be7280c529a1d175, which is narrower than
the scope of `testapp` ('session').
Since `testapp` only depends only on `app`, it is safe to make it's scope match
`app`.

Fix ScopeMismatch error when testing

---

{{cookiecutter.app_name}}/manage.py
{{cookiecutter.app_name}}/tests/conftest.py
{{cookiecutter.app_name}}/tests/factories.py
{{cookiecutter.app_name}}/tests/test_config.py
{{cookiecutter.app_name}}/tests/test_forms.py
{{cookiecutter.app_name}}/tests/test_models.py
{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/app.py
{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/database.py
{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/public/__init__.py
{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/public/forms.py
{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/public/views.py
{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/settings.py
{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/user/__init__.py
{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/user/forms.py
{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/user/models.py
{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/user/views.py
{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/utils.py

- Add the UTF-8 marker to files without it.
- Fix some hanging indents.
- Change ''' into """ in docstrings.
- Enforce two blank line rule.

Python code clean-up (PEP-8 related and other)

---

{{cookiecutter.app_name}}/.gitignore

I looked for the minimal `env` related values suggested by gitignore.io which says just `env/`. They also recommend the following for virtualenv but I left it out:
```
.Python
[Bb]in
[Ii]nclude
[Ll]ib
[Ss]cripts
pyvenv.cfg
pip-selfcheck.json
```
Closes #44.

Only ignoring the env directory to avoid conflicts with alembic's env.py

---

{{cookiecutter.app_name}}/manage.py

Two new useful commands for manage.py. `m urls` lists all URLs (like `rake routes` in Rails). `m clean` gets rid of .pyc files.

Add `urls` and `clean` commands to manage.py

---

{{cookiecutter.app_name}}/requirements/prod.txt

psycopg2 required by postgresql on production environments

Add psycopg2 to production requirements

---

{{cookiecutter.app_name}}/manage.py

It seems that we should init the extension first, am I miss something here?

Init the flask-migrate extension first

---

{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/templates/public/register.html

Switch Register CSRF protect from form.hidden_tag to input hidden
value=csrf_token.
I don't understand why this is necessary, as form.hidden_tag works
in other situations. This may be a symptom of an aliasing issue. However, it was
the solution applied to fix login in a previous commit as described in
https://github.com/sloria/cookiecutter-flask/issues/34.
Without this change, the CSRF value is "None".

Switch CSRF token rendering mechanism.

---

README.rst
{{cookiecutter.app_name}}/README.rst
{{cookiecutter.app_name}}/autoapp.py

Use the new FLASK_DEBUG environment variable which is standard as of Flask 0.11, in order to control the use of dev or prod config.
Need to set this anyway, in order for "flask run" to use reloader and no concurrency.

Use FLASK_DEBUG instead of MYFLASKAPP_ENV

---

{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/user/models.py

Hello,
I was running into an issue with an "Invalid Salt"  exception when checking user passwords with a Postgresql backend.  I was able to track the issue down to SqlAlchemy casting the hash to the incorrect type when `db.String` is specified.  Saving it as a `db.Binary` type because it is a Byte string remedies this issue.  
More info here: http://stackoverflow.com/a/37032208

Fix for Bcrypt and SqlAlchemy type casting in Postgres

---

{{cookiecutter.app_name}}/requirements/prod.txt

Setuptools and wheel are unnecessary in the requirements file and cause some PaaS to fail (namely Heroku)
Removing these has no downsides (as they will be present in a system with Python installed) and prevents that error from confusing new people.  
From Heroku:
```
remote:  !     The package setuptools/distribute is listed in requirements.txt.
remote:  !     Please remove to ensure expected behavior. 
...<snip>...
remote:            Uninstalling setuptools-25.2.0:
remote:              Successfully uninstalled setuptools-25.2.0
remote:          Rolling back uninstall of setuptools
remote:        Exception:
remote:        Traceback (most recent call last):
remote:          File "/app/.heroku/python/lib/python2.7/site-packages/pip-8.1.2-py2.7.egg/pip/basecommand.py", line 215, in main …
```

specifiying setuptools/wheel will cause deployment to fail in Heroku

---

{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/app.py

This passes `app_name` instead of the current `app_name.app` to Flask. Please see `About the First Parameter` note in http://flask.pocoo.org/docs/0.11/api/

Pass `app_name` instead of `app_name.app` to Flask

---

{{cookiecutter.app_name}}/.travis.yml

The environment variable `FLASK_APP` must be set for proper initialization with Travis CI.
See difference from the first and last build [here](https://travis-ci.org/wernersa/wersav_web/builds).

Fixed flask app initialization for Travis CI

---

{{cookiecutter.app_name}}/package.json

Specify minimum viable version of node in the package.json file.
This should help triage issues like #213 and #218 which are due to people running the project with very old installs of nodejs.

package.json: specify engines with node>=4

---

{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/database.py

Since the alias have been defined, it is better to make the code clear and consistent

remove the db. by using the alias

---

{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/templates/public/register.html

Not sure if you are not using the [csrf-helper from flask-wtf](http://flask-wtf.readthedocs.io/en/stable/quickstart.html) for a specific reason. In case you do, then sorry for the noise. Otherwise here is a PR which uses the helper.
`<input type="hidden" name="csrf_token" value="IjRjMGI2NTAwNTg5ZmNlMDY4YWNjM2I3OTIxZDhjNjczMjBhNTJiNTAi.DZ-BMA.-57kVA-q_uwyhQkE9yt-X5NIL0s"/>`
`<input id="csrf_token" name="csrf_token" type="hidden" value="IjRjMGI2NTAwNTg5ZmNlMDY4YWNjM2I3OTIxZDhjNjczMjBhNTJiNTAi.DZ-Ayg.F-yS07h6u0zSZZyQIj4UymcLSbs">`

Using flask-wtf helper for csrf token field

---

{{cookiecutter.app_name}}/package.json

Fixes issue #336, currently `webpack-dev-server` exits with an error due to changes
in the webpack api and `webpack-cli` being split out in webpack 4. `webpack-dev-server` 3.x does not appear to support webpack 2.6.

Downgrade webpack-dev-server pending webpack4 support.

---

{{cookiecutter.app_name}}/package.json

If `pipenv` was selected during cookiecutter setup, then `npm run flask-server` should run `pipenv run flask run`. This commit changes `package.json` npm scripts accordingly.

Fix `flask-server` script to be run through pipenv

---

{{cookiecutter.app_name}}/Pipfile

Resolves https://github.com/cookiecutter-flask/cookiecutter-flask/issues/490. The introduction of the pinned python version resulted in Dependabot being unable to parse the Pipfile.
Tested by running Dependabot on my fork; the bot successfully parsed the Pipfile after this change.

Remove pinned python version from pipfile

---

{{cookiecutter.app_name}}/requirements/prod.txt

Beginning with the 2.8 release of `psycopg` (introduced into this project by PR https://github.com/cookiecutter-flask/cookiecutter-flask/pull/488), the `psycopg` package is built from source, requiring the user to install system dependencies. Switch to using psycopg-binary package to maintain pre-2.8 behavior of installing from wheel. There is [discussion](http://initd.org/psycopg/articles/2018/02/08/psycopg-274-released/) on the tradeoffs between `psycopg2` and `psycopg2-binary`; I'm defaulting to the binary version to decrease barrier to entry for new users of this project.

Use binary version of psycopg

---

.travis.yml
Dockerfile
README.rst
cookiecutter-docker.sh
cookiecutter.json
hooks/post_gen_project.py
hooks/pre_gen_project.py

Builds the cookiecutter project entirely in docker via
```bash
$ ./cookiecutter-docker.sh
```
Expands the Travis CI test matrix to ensure all supported combinations of Python and Node are tested. In a future PR, may investigate leveraging docker-compose to run the Travis test suite for consistency with the process for launching the app in docker.

Allow cookiecutter build in docker

---

.travis.yml
cookiecutter.json
hooks/post_gen_project.py
hooks/pre_gen_project.py
tasks.py
{{cookiecutter.app_name}}/.isort.cfg
{{cookiecutter.app_name}}/.travis.yml
{{cookiecutter.app_name}}/Pipfile
{{cookiecutter.app_name}}/README.rst
{{cookiecutter.app_name}}/package.json
{{cookiecutter.app_name}}/requirements/dev.txt
{{cookiecutter.app_name}}/setup.cfg
{{cookiecutter.app_name}}/tests/conftest.py
{{cookiecutter.app_name}}/tests/factories.py
{{cookiecutter.app_name}}/tests/settings.py
{{cookiecutter.app_name}}/tests/test_forms.py
{{cookiecutter.app_name}}/tests/test_functional.py
{{cookiecutter.app_name}}/tests/test_models.py
{{cookiecutter.app_name}}/webpack.config.js
{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/app.py
{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/commands.py
{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/database.py
{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/public/forms.py
{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/public/views.py
{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/settings.py
{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/user/forms.py
{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/user/models.py
{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/user/views.py
{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/utils.py

This is a larger PR that implements `black` formatting. Changes are split across two commits: the first commit contains functional changes to the code, while the second contains only formatting changes.
Aside from the formatting changes, the two main changes are:
* Remove support for Python < 3.6 (`black` requires >= 3.6)
* Change default value for sorting imports (previously did not sort by default, but now it does)

Add black formatting

---

{{cookiecutter.app_name}}/Pipfile
{{cookiecutter.app_name}}/requirements/dev.txt

This project uses `flake8-docstrings`, which contained an unpinned dependency on `pydocstyle`. A breaking change in `pydocstyle` is causing our CI pipelines to fail erroneously. This PR pins `pydocstyle`; this change will be reverted once a fix is pushed to `flake8-docstrings`.

Implement temporary fix for breaking change in pydocstyle

---

{{cookiecutter.app_name}}/tests/conftest.py

Fix for issue mentioned in https://github.com/cookiecutter-flask/cookiecutter-flask/issues/546.
It is caused by app logger.
Same fix was introduced in googleapis/oauth2client: [Silence flask app logger during tests](https://github.com/googleapis/oauth2client/pull/566/files)

Fix flask test command

---

{{cookiecutter.app_name}}/.travis.yml

I've add `DATABASE_URL` and `SECRET_KEY` because I received errors on Travis (due to missing environmental variables in `settings.py`)

Fix missing environmental variables in travis.yml

---

{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/user/models.py

The deprecated `Binary` class is used in `User` model. I've run tests on CI with `LargeBinary` instead of `Binary` class used and there was no warning. I've checked it on my hobby project that password is stored properly.
Source code of the warning: https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/sql/sqltypes.py#L986.

Update deprecated database field

---

{{cookiecutter.app_name}}/Pipfile
{{cookiecutter.app_name}}/requirements/dev.txt

Previous versions of `flake8-docstrings` had an unpinned dependency on `pydocstyle`, causing compatibility issues. The most recent version of `flake8-docstrings` pinned the dependency, and as such we no longer need to manually pin `pydocstyle`.

Remove pinned pydocstyle version

---

{{cookiecutter.app_name}}/Pipfile
{{cookiecutter.app_name}}/requirements/prod.txt

Dependabot fails when it encounters a jinja template. Given that there's only one package that's conditionally being installed, let's just add it for everyone.

Remove jinja templating from requirements

---

{{cookiecutter.app_name}}/README.rst

It might be confusing for beginners following the docs if the `pipenv shell` is not there (that is, in case pinenv is being used)

Adds pipenv shell to docs

---

hooks/pre_gen_project.py
hooks/utils.py

There have been two recent issues raised by users who generate a project with an incompatible version of Python: (#616 and #642).
The README contains information about the supported versions of Python, but trying to execute the cookiecutter with an incompatible version raises a SyntaxError, rather than a warning about the Python version.
Therefore, this adds an addition check to the `pre_gen_project` hook to prompt users to use a more recent version of Python.

Warn when running Cookiecutter with incompatible python version

---

{{cookiecutter.app_name}}/.env.example

This prevents the environs library from failing to parse the .env file, fixing bug #660

Move SEND_FILE_MAX_AGE_DEFAULT comment to line above

---

{{cookiecutter.app_name}}/webpack.config.js

This commit prevents the error: "Error: Cannot find module 'babel-preset-env'".
For details see https://github.com/cookiecutter-flask/cookiecutter-flask/issues/666

Prevent "Cannot find module 'babel-preset-env'"

---

{{cookiecutter.app_name}}/README.md
{{cookiecutter.app_name}}/package.json

As per #648 , in windows, environment variables are set using a `SET` command. Propose to add `-windows` versions of start/build for those users

Include windows npm commands

---

{{cookiecutter.app_name}}/README.md

In a clean setup, and following all the instructions, leads to an error of missing `SEND_FILE_MAX_AGE_DEFAULT`. 
I added a line in the readme setting that variable to the example found in `.env.example`
Looking at the issues, and it seems some people had the same issue:
https://github.com/cookiecutter-flask/cookiecutter-flask/issues/790#issuecomment-643551198

Update heroku docs

---

{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/database.py
{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/user/models.py

`__table_args__ = {"extend_existing": True}` breaks a lot of scenarios for inheritance, which are relatively common. This seems to have happened after SQLAlchemy 2.3.2 according to #230
Removing table_args, and we get `Table 'association' is already defined for this MetaData instance.  Specify 'extend_existing=True' to redefine options and columns on an existing Table object.`
This might not be the nicest way to fix the problem because it uses inheritance, but I could not find any better way without fiddling with SQLAlchemy internals. This might even be a case to escalate this to SQLAlchemy as a bug (ie, incompatibility of Mixins and Inheritance)
Another alternative is to have the Primary key directly in `Model` but that might be way too intrusive since a lot of people like to have …

Migrate SurrogatePK to abstract class

---

{{cookiecutter.app_name}}/.github/workflows/lint.yaml

When I used this cookiecutter yesterday I kept getting errors in GitHub actions. I was using the use_pipenv option.
I found that the following changes needed to be made to the lint.yaml file.
I tested out the changes with a new blank app test and pushed it to GitHub and the GitHub actions worked (https://github.com/nstoik/test_app)

Fix GitHub actions with pipenv

---

.github/workflows/lint.yaml
cookiecutter.json
tasks.py

There have been a few regressions from snippets of demo code (like `my_flask_app`) that were accidentally committed instead of the template value. This PR adds a lint that prevents this.

Add lint for committed example code

---

.github/workflows/lint.yaml
README.md
tasks.py
{{cookiecutter.app_name}}/Dockerfile
{{cookiecutter.app_name}}/package.json
{{cookiecutter.app_name}}/webpack.config.js

Fixes issues introduced by upgrading Webpack to 5.x. Additionally, it updates the CI pipeline to add a step that builds the Docker image associated with the generated project, which would have caught this issue. 
Closes https://github.com/cookiecutter-flask/cookiecutter-flask/issues/954
Closes https://github.com/cookiecutter-flask/cookiecutter-flask/issues/955

Fix webpack breaking changes

---

{{cookiecutter.app_name}}/README.md

With GitHub changes, it makes sense to switch `master` to `main`.

Update README.md to  heroku main instead of master

---

{{cookiecutter.app_name}}/docker-compose.yml

Before commands such as `docker-compose run --rm manage test` failed with an error message:
Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"flask\": executable file not found in $PATH": unknown

fix entry point for 'manage' container

---

{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/templates/nav.html

Thanks for this project! I was having an issue where the Font-Awesome sign-out icon wasn't showing up for me. I looked at the icon list and it appears that `fa-sign-out` is a PRO icon, whereas `fa-sign-out-alt` is free. This PR changes the icon to use the free version so it shows up once cookie-cut.

Bugfix: Use free sign out FA icon

---

{{cookiecutter.app_name}}/assets/js/main.js

New projects fail `Run Node lints` step out of box because `assets/js/main.js` does not conform to the AirBnB standard
https://github.com/airbnb/javascript#modules

fixes assets/js/main.js require() to conform with AirBnB standard

---

{{cookiecutter.app_name}}/tests/factories.py
{{cookiecutter.app_name}}/tests/test_forms.py
{{cookiecutter.app_name}}/tests/test_models.py
{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/user/models.py

Converted password field to a hybrid_property, so that when the field is set or updated it is automatically encrypted utilizing `bcrypt`. This approach also eliminates the need for an extra step (i.e. calling `.set_password`) during account creation/update
Closes #158

Fixed password update handling

---

{{cookiecutter.app_name}}/requirements/prod.txt
{{cookiecutter.app_name}}/tests/test_forms.py

Fixes the said test for newer version of the `email_validator` pip package
Closes #1394

tests/test_forms.py: fix 'test_validate_success'

---

.github/ISSUE_TEMPLATE/1-bug-report.md
.github/workflows/lint.yml
README.md
cookiecutter_spec.py

Removes support for the Node 16 LTS, which is coming up on the end of support (should not be used for new projects), and was causing some issues in #1435

Update to currently supported node LTS versions

---

{{cookiecutter.app_name}}/README.md

**Currently:**
`docker-compose run --rm manage db shell`
results in:
```
Error: No such command 'shell'.
```
**Suggested:**
`docker-compose run --rm manage shell`
results in:
```
Creating foobar_manage_run ... done
Loading .env environment variables...
Python 3.11.4 (main, Jun 13 2023, 15:34:37) [GCC 8.3.0] on linux
App: foobar
Instance: /app/instance
>>>
```

fix shell command in README.md
